### PR TITLE
Created Hack-A-Sat-2021 Folder writeups

### PR DESCRIPTION
**Pull request by AmieDD**
Created a folder for the Hack-A-Sat 2021 writeups

### CODE REVIEW

**Comment by mossmann** [comment]
Did you intend the .vs folder to be included?

**Comment by AmieDD** [comment]
@mossmann dang it. I forgot to include the git ignore. Thanks for reviewing. I'll update the PR.

**Comment by mossmann** [comment]
Thanks for the .gitignore! Do you want to remove the two .vs/* from this too, or do you actually want those in the repo?

**Comment by mossmann** [comment]
I think your intent was to remove the .vs directory entirely and to have the .gitignore cover the top level .vs, so I redid things in that way in #6. I've requested your review of #6 in case I was wrong about your intent. If you like #6, we can squash and merge #6 and close this one.

**Comment by mossmann** [comment]
merged in #6

**Pull request closed without merging**
